# ex: set ro:
# DO NOT EDIT.
# generated by smc (http://smc.sourceforge.net/)
# from file : AppClass.sm

import statemap


class AppClassState(statemap.State):

    def Entry(self, fsm):
        pass

    def Exit(self, fsm):
        pass

    def EOS(self, fsm, counter):
        self.Default(fsm)

    def symb(self, fsm, c, counter):
        self.Default(fsm)

    def Default(self, fsm):
        msg = "\n\tState: %s\n\tTransition: %s" % (
            fsm.getState().getName(), fsm.getTransition())
        raise statemap.TransitionUndefinedException(msg)

class Map1_Default(AppClassState):

    def symb(self, fsm, c, counter):
        fsm.getState().Exit(fsm)
        fsm.setState(Map1.Error)
        fsm.getState().Entry(fsm)


    def EOS(self, fsm, counter):
        ctxt = fsm.getOwner()
        fsm.getState().Exit(fsm)
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(Map1.Error)
            fsm.getState().Entry(fsm)


class Map1_Start(Map1_Default):

    def symb(self, fsm, c, counter):
        ctxt = fsm.getOwner()
        if counter == 0 and c == "m" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 1 and c == "a" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 2 and c == "i" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 3 and c == "l" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 4 and c == "t" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 5 and c == "o" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 6 and c == ":" :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.ResetCounter()
            finally:
                fsm.setState(Map1.UserName)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.symb(self, fsm, c, counter)
        
class Map1_UserName(Map1_Default):

    def symb(self, fsm, c, counter):
        ctxt = fsm.getOwner()
        if (c >= "a" and c<="z") or (c >= "A" and c <= "Z") or (c >= "0" and c <= "9") :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif c == "@" :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.Save_name()
                ctxt.ResetCounter()
            finally:
                fsm.setState(Map1.ServName)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.symb(self, fsm, c, counter)
        
class Map1_ServName(Map1_Default):

    def symb(self, fsm, c, counter):
        ctxt = fsm.getOwner()
        if (c >= "a" and c<="z") or (c >= "A" and c <= "Z") or (c >= "0" and c <= "9") :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif c == "." :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.ResetCounter()
            finally:
                fsm.setState(Map1.ZoneName)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.symb(self, fsm, c, counter)
        
class Map1_ZoneName(Map1_Default):

    def symb(self, fsm, c, counter):
        ctxt = fsm.getOwner()
        if (c >= "a" and c<="z") or (c >= "A" and c <= "Z") :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif c == "?" :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.ResetCounter()
            finally:
                fsm.setState(Map1.GetSubject)
                fsm.getState().Entry(fsm)
        elif c == '\n' :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.Acceptable()
            finally:
                fsm.setState(Map1.OK)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.symb(self, fsm, c, counter)
        
class Map1_GetSubject(Map1_Default):

    def symb(self, fsm, c, counter):
        ctxt = fsm.getOwner()
        if counter == 0 and c == "s" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 1 and c == "u" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 2 and c == "b" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 3 and c == "j" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 4 and c == "e" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 5 and c == "c" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 6 and c == "t" :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif counter == 7 and c == "=" :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.ResetCounter()
            finally:
                fsm.setState(Map1.Subj)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.symb(self, fsm, c, counter)
        
class Map1_Subj(Map1_Default):

    def symb(self, fsm, c, counter):
        ctxt = fsm.getOwner()
        if ((c >= "a" and c<="z") or (c >= "A" and c<="Z") or (c >= "0" and c <= "9")) and counter <= 64 :
            endState = fsm.getState()
            fsm.clearState()
            try:
                ctxt.Counter()
            finally:
                fsm.setState(endState)
        elif c == '\n' and counter <= 64 :
            fsm.getState().Exit(fsm)
            fsm.clearState()
            try:
                ctxt.Acceptable()
            finally:
                fsm.setState(Map1.OK)
                fsm.getState().Entry(fsm)
        else:
            Map1_Default.symb(self, fsm, c, counter)
        
class Map1_OK(Map1_Default):
    pass

class Map1_Error(Map1_Default):

    def EOS(self, fsm, counter):
        ctxt = fsm.getOwner()
        endState = fsm.getState()
        fsm.clearState()
        try:
            ctxt.Unacceptable()
        finally:
            fsm.setState(endState)


class Map1(object):

    Start = Map1_Start('Map1.Start', 0)
    UserName = Map1_UserName('Map1.UserName', 1)
    ServName = Map1_ServName('Map1.ServName', 2)
    ZoneName = Map1_ZoneName('Map1.ZoneName', 3)
    GetSubject = Map1_GetSubject('Map1.GetSubject', 4)
    Subj = Map1_Subj('Map1.Subj', 5)
    OK = Map1_OK('Map1.OK', 6)
    Error = Map1_Error('Map1.Error', 7)
    Default = Map1_Default('Map1.Default', -1)

class AppClass_sm(statemap.FSMContext):

    def __init__(self, owner):
        statemap.FSMContext.__init__(self, Map1.Start)
        self._owner = owner

    def __getattr__(self, attrib):
        def trans_sm(*arglist):
            self._transition = attrib
            getattr(self.getState(), attrib)(self, *arglist)
            self._transition = None
        return trans_sm

    def enterStartState(self):
        self._state.Entry(self)

    def getOwner(self):
        return self._owner

# Local variables:
#  buffer-read-only: t
# End:
